2022-03-04 21:38:57,176 ERROR: Exception on /download_table/4 [GET] [in C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py:1457]
Traceback (most recent call last):
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\62821\Documents\GitHub\4p-flask\app\routes.py", line 329, in download_table
    return excel.make_response_from_query_sets(query_sets, column_names, "xlsx")
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_webio\__init__.py", line 434, in make_response_from_query_sets
    file_stream = pe.save_as(query_sets=query_sets, column_names=column_names,
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\core.py", line 77, in save_as
    sheet_stream = sources.get_sheet_stream(**source_keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\internal\core.py", line 21, in get_sheet_stream
    sheets = a_source.get_data()
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel\plugins\sources\querysets.py", line 72, in get_data
    data = get_data(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 86, in get_data
    data, _ = _get_data(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 105, in _get_data
    return load_data(**keywords)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\io.py", line 208, in load_data
    result[key] = list(result[key])
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\sheet.py", line 68, in to_array
    for column_index, cell_value in enumerate(
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\reader.py", line 126, in column_iterator
    yield from self._native_sheet.column_iterator(row)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\database\querysets.py", line 54, in column_iterator
    value = get_simple_attribute(row, column)
  File "C:\Users\62821\belajar_python\flask\env\lib\site-packages\pyexcel_io\database\querysets.py", line 72, in get_simple_attribute
    value = getattr(row, attribute)
AttributeError: 'Post' object has no attribute 'user_name'
2022-03-04 21:39:37,101 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-04 23:57:08,536 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-05 00:00:20,698 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-05 00:16:41,140 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-05 00:17:43,112 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-05 00:17:51,509 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-05 00:18:02,563 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-05 13:17:42,026 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-05 16:53:49,328 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-06 01:57:07,880 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-06 01:58:38,212 INFO: Blog startup [in C:\Users\62821\Documents\GitHub\4p-flask\app\__init__.py:54]
2022-03-06 09:43:20,263 INFO: Blog startup [in C:\Users\62821\Documents\NGODING\Python\4P_Flask\app\__init__.py:54]
2022-03-06 09:45:59,848 INFO: Blog startup [in C:\Users\62821\Documents\NGODING\Python\4P_Flask\app\__init__.py:54]
2022-03-06 10:07:58,430 INFO: Blog startup [in C:\Users\62821\belajar_python\flask\app\__init__.py:54]
2022-03-06 10:12:13,373 INFO: Blog startup [in C:\Users\62821\belajar_python\flask\app\__init__.py:54]
2022-03-06 10:15:31,981 INFO: Blog startup [in C:\Users\62821\belajar_python\flask\app\__init__.py:54]
2022-03-06 16:59:25,443 INFO: Blog startup [in C:\Users\62821\belajar_python\flask\app\__init__.py:54]
